/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.AccessorTypes

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 設定自定義存取權限參數
 *
 * @param type 
 * @param ids 可存取此頻道的RoleIds/UserId
 */
@Parcelize


data class AccessorParam (

    @Json(name = "type")
    val type: AccessorTypes? = null,

    /* 可存取此頻道的RoleIds/UserId */
    @Json(name = "ids")
    val ids: kotlin.collections.List<kotlin.String>? = null

) : Parcelable

