/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.BanPeriodOption

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param userid 
 * @param periodOption 
 */
@Parcelize


data class BanParam (

    @Json(name = "userid")
    val userid: kotlin.String? = null,

    @Json(name = "periodOption")
    val periodOption: BanPeriodOption? = null

) : Parcelable

