/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.AuthType
import com.cmoney.fanciapi.fanci.model.BuffType

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param scopeType 
 * @param buffType 
 * @param name 
 * @param description 
 * @param startDateTime 
 * @param endDateTime 
 */
@Parcelize


data class BuffStatus (

    @Json(name = "scopeType")
    val scopeType: AuthType? = null,

    @Json(name = "buffType")
    val buffType: BuffType? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "startDateTime")
    val startDateTime: kotlin.Long? = null,

    @Json(name = "endDateTime")
    val endDateTime: kotlin.Long? = null

) : Parcelable

