/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param categoryId 
 * @param channelIds 
 */


data class CategoryOrder (

    @Json(name = "categoryId")
    val categoryId: kotlin.String? = null,

    @Json(name = "channelIds")
    val channelIds: kotlin.collections.List<kotlin.String>? = null

)

