/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.Channel

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 分類ID
 * @param name 分類標籤名稱
 * @param weight 排序權重
 * @param createUnixTime 分類建立時間
 * @param updateUnixTime 分類更新時間
 * @param creatorId 建立分類UserId
 * @param isDeleted 是否被刪除
 * @param groupId 所屬社團
 * @param channels 分類下的群組
 */
@Parcelize


data class Category (

    /* 分類ID */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* 分類標籤名稱 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* 排序權重 */
    @Json(name = "weight")
    val weight: kotlin.Long? = null,

    /* 分類建立時間 */
    @Json(name = "createUnixTime")
    val createUnixTime: kotlin.Long? = null,

    /* 分類更新時間 */
    @Json(name = "updateUnixTime")
    val updateUnixTime: kotlin.Long? = null,

    /* 建立分類UserId */
    @Json(name = "creatorId")
    val creatorId: kotlin.String? = null,

    /* 是否被刪除 */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    /* 所屬社團 */
    @Json(name = "groupId")
    val groupId: kotlin.String? = null,

    /* 分類下的群組 */
    @Json(name = "channels")
    val channels: kotlin.collections.List<Channel>? = null

) : Parcelable

