/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.ChannelPrivacy
import com.cmoney.fanciapi.fanci.model.ChannelTabType

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 新增頻道參數
 *
 * @param name 頻道名稱
 * @param privacy 
 * @param tabs 頻道開啟類別(順序依照提供的順序排序)
 */
@Parcelize


data class ChannelParam (

    /* 頻道名稱 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "privacy")
    val privacy: ChannelPrivacy? = null,

    /* 頻道開啟類別(順序依照提供的順序排序) */
    @Json(name = "tabs")
    val tabs: kotlin.collections.List<ChannelTabType>? = null

) : Parcelable

