/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 頻道的權限列表
 *
 * @param canRead 
 * @param canPost 
 * @param canReply 
 * @param canEmoji 
 * @param canManage 
 * @param canCopy 
 * @param canBlock 
 * @param canReport 
 * @param canTakeback 
 */
@Parcelize


data class ChannelPermission (

    @Json(name = "canRead")
    val canRead: kotlin.Boolean? = null,

    @Json(name = "canPost")
    val canPost: kotlin.Boolean? = null,

    @Json(name = "canReply")
    val canReply: kotlin.Boolean? = null,

    @Json(name = "canEmoji")
    val canEmoji: kotlin.Boolean? = null,

    @Json(name = "canManage")
    val canManage: kotlin.Boolean? = null,

    @Json(name = "canCopy")
    val canCopy: kotlin.Boolean? = null,

    @Json(name = "canBlock")
    val canBlock: kotlin.Boolean? = null,

    @Json(name = "canReport")
    val canReport: kotlin.Boolean? = null,

    @Json(name = "canTakeback")
    val canTakeback: kotlin.Boolean? = null

) : Parcelable

