/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.Category
import com.cmoney.fanciapi.fanci.model.ChannelPrivacy
import com.cmoney.fanciapi.fanci.model.ChannelTabType

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 頻道
 *
 * @param id 頻道Id
 * @param creatorId 頻道創立者
 * @param channelType 
 * @param name 頻道命名
 * @param createUnixTime 頻道建立時間
 * @param updateUnixTime 頻道更新時間
 * @param weight 排序權重
 * @param groupId 頻道所屬社團Id
 * @param category 
 * @param privacy 
 */
@Parcelize


data class Channel (

    /* 頻道Id */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* 頻道創立者 */
    @Json(name = "creatorId")
    val creatorId: kotlin.String? = null,

    @Json(name = "channelType")
    val channelType: ChannelTabType? = null,

    /* 頻道命名 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* 頻道建立時間 */
    @Json(name = "createUnixTime")
    val createUnixTime: kotlin.Long? = null,

    /* 頻道更新時間 */
    @Json(name = "updateUnixTime")
    val updateUnixTime: kotlin.Long? = null,

    /* 排序權重 */
    @Json(name = "weight")
    val weight: kotlin.Long? = null,

    /* 頻道所屬社團Id */
    @Json(name = "groupId")
    val groupId: kotlin.String? = null,

    @Json(name = "category")
    val category: Category? = null,

    @Json(name = "privacy")
    val privacy: ChannelPrivacy? = null

) : Parcelable

