/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.Channel

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 分頁
 *
 * @param haveNextPage 是否有下一頁
 * @param nextWeight 下一個詢問權重
 * @param items 結果清單
 */
@Parcelize


data class ChannelPaging (

    /* 是否有下一頁 */
    @Json(name = "haveNextPage")
    val haveNextPage: kotlin.Boolean? = null,

    /* 下一個詢問權重 */
    @Json(name = "nextWeight")
    val nextWeight: kotlin.Long? = null,

    /* 結果清單 */
    @Json(name = "items")
    val items: kotlin.collections.List<Channel>? = null

) : Parcelable

