/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.AuthBulliten
import com.cmoney.fanciapi.fanci.model.ChannelAuthType

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param authType 
 * @param title 
 * @param icon 
 * @param bullitens 
 */
@Parcelize


data class ChannelAccessOptionModel (

    @Json(name = "authType")
    val authType: ChannelAuthType? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "icon")
    val icon: kotlin.String? = null,

    @Json(name = "bullitens")
    val bullitens: kotlin.collections.List<AuthBulliten>? = null

) : Parcelable

