/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.GroupMember
import com.cmoney.fanciapi.fanci.model.IEmojiCount
import com.cmoney.fanciapi.fanci.model.MediaIChatContent
import com.cmoney.fanciapi.fanci.model.MessageType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param author 
 * @param replyMessage 
 * @param content 
 * @param emojiCount 
 * @param id 
 * @param isDeleted 
 * @param createUnixTime 
 * @param updateUnixTime 
 * @param serialNumber 
 * @param messageType 
 */


data class ChatMessage (

    @Json(name = "author")
    val author: GroupMember? = null,

    @Json(name = "replyMessage")
    val replyMessage: ChatMessage? = null,

    @Json(name = "content")
    val content: MediaIChatContent? = null,

    @Json(name = "emojiCount")
    val emojiCount: IEmojiCount? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    @Json(name = "createUnixTime")
    val createUnixTime: kotlin.Long? = null,

    @Json(name = "updateUnixTime")
    val updateUnixTime: kotlin.Long? = null,

    @Json(name = "serialNumber")
    val serialNumber: kotlin.Long? = null,

    @Json(name = "messageType")
    val messageType: MessageType? = null

)

