/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.Media

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param replyMessageId 回覆的messageid
 * @param text 文字訊息內容
 * @param medias 附帶媒體內容
 * @param votingIds 投票活動
 */
@Parcelize


data class ChatMessageParam (

    /* 回覆的messageid */
    @Json(name = "replyMessageId")
    val replyMessageId: kotlin.String? = null,

    /* 文字訊息內容 */
    @Json(name = "text")
    val text: kotlin.String? = null,

    /* 附帶媒體內容 */
    @Json(name = "medias")
    val medias: kotlin.collections.List<Media>? = null,

    /* 投票活動 */
    @Json(name = "votingIds")
    val votingIds: kotlin.collections.List<kotlin.String>? = null

) : Parcelable

