/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.Media
import com.cmoney.fanciapi.fanci.model.MessageType

import com.squareup.moshi.Json

/**
 * 聊天訊息內容
 *
 * @param replyMessageId 回覆的messageid
 * @param text 聊天訊息內容
 * @param medias 聊天訊息內容
 * @param messageType 
 */


data class ChatMessageParam (

    /* 回覆的messageid */
    @Json(name = "replyMessageId")
    val replyMessageId: kotlin.String? = null,

    /* 聊天訊息內容 */
    @Json(name = "text")
    val text: kotlin.String? = null,

    /* 聊天訊息內容 */
    @Json(name = "medias")
    val medias: kotlin.collections.List<Media>? = null,

    @Json(name = "messageType")
    val messageType: MessageType? = null

)

