/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: themeFanciBlue,themeSmokePink,themeMidnightBlue,themeClassicGreen,themeNeonBlack
 */

enum class ColorTheme(val value: kotlin.String) {

    @Json(name = "ThemeFanciBlue")
    themeFanciBlue("ThemeFanciBlue"),

    @Json(name = "ThemeSmokePink")
    themeSmokePink("ThemeSmokePink"),

    @Json(name = "ThemeMidnightBlue")
    themeMidnightBlue("ThemeMidnightBlue"),

    @Json(name = "ThemeClassicGreen")
    themeClassicGreen("ThemeClassicGreen"),

    @Json(name = "ThemeNeonBlack")
    themeNeonBlack("ThemeNeonBlack");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ColorTheme) "$data" else null

        /**
         * Returns a valid [ColorTheme] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ColorTheme? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

