/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param name 
 * @param hexColorCode 
 * @param displayName 
 */
@Parcelize


data class Color (

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "hexColorCode")
    val hexColorCode: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null

) : Parcelable

