/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param defaultImages 
 */
@Parcelize


data class DefaultImageResource (

    @Json(name = "defaultImages")
    val defaultImages: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>? = null

) : Parcelable

