/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 刪除投票參數
 *
 * @param votingIds 投票 ID 陣列
 */
@Parcelize


data class DeleteVotingsParam (

    /* 投票 ID 陣列 */
    @Json(name = "votingIds")
    val votingIds: kotlin.collections.List<kotlin.String>? = null

) : Parcelable

