/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 編輯頻道參數
 *
 * @param name 頻道名稱
 */
@Parcelize


data class EditChannelParam (

    /* 頻道名稱 */
    @Json(name = "name")
    val name: kotlin.String

) : Parcelable

