/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param name 命名
 * @param isNeedApproval 
 */
@Parcelize


data class EditChannelParam (

    /* 命名 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "isNeedApproval")
    val isNeedApproval: kotlin.Boolean? = null

) : Parcelable

