/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param roleId 
 * @param name 
 * @param cmoneyDataId 
 * @param permissionIds 
 */


data class FanciRole (

    @Json(name = "roleId")
    val roleId: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "cmoneyDataId")
    val cmoneyDataId: kotlin.String? = null,

    @Json(name = "permissionIds")
    val permissionIds: kotlin.collections.List<kotlin.Int>? = null

)

