/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param permissionId 
 * @param name 權限名稱
 * @param description 權限描述
 * @param level 0. group(space) level  1. channel(board) level
 */


data class FanciPermission (

    @Json(name = "permissionId")
    val permissionId: kotlin.Int? = null,

    /* 權限名稱 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* 權限描述 */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* 0. group(space) level  1. channel(board) level */
    @Json(name = "level")
    val level: kotlin.Int? = null

)

