/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.GroupRequirementAnswer

import com.squareup.moshi.Json

/**
 * 申請加入社團參數
 *
 * @param answers 回答
 */


data class GroupApplyParam (

    /* 回答 */
    @Json(name = "answers")
    val answers: kotlin.collections.List<GroupRequirementAnswer>

)

