/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.GroupRequirementQuestionType

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param question 
 * @param type 
 */
@Parcelize


data class GroupRequirementQuestion (

    @Json(name = "question")
    val question: kotlin.String? = null,

    @Json(name = "type")
    val type: GroupRequirementQuestionType? = null

) : Parcelable

