/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.ApplyStatus
import com.cmoney.fanciapi.fanci.model.IGroupRequirementAnswer
import com.cmoney.fanciapi.fanci.model.User

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 社團申請
 *
 * @param id Id
 * @param groupId 
 * @param user 
 * @param hasVipRole 是否為社團VIP
 * @param answers 回答
 * @param status 
 * @param updateUnixTime 更新時間
 * @param weight 
 * @param wasKicked 
 */
@Parcelize


data class GroupRequirementApply (

    /* Id */
    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "groupId")
    val groupId: kotlin.String? = null,

    @Json(name = "user")
    val user: User? = null,

    /* 是否為社團VIP */
    @Json(name = "hasVipRole")
    val hasVipRole: kotlin.Boolean? = null,

    /* 回答 */
    @Json(name = "answers")
    val answers: kotlin.collections.List<IGroupRequirementAnswer>? = null,

    @Json(name = "status")
    val status: ApplyStatus? = null,

    /* 更新時間 */
    @Json(name = "updateUnixTime")
    val updateUnixTime: kotlin.Long? = null,

    @Json(name = "weight")
    val weight: kotlin.Long? = null,

    @Json(name = "wasKicked")
    val wasKicked: kotlin.Boolean? = null

) : Parcelable

