/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.ApplyStatus

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 申請狀態參數
 *
 * @param status 
 * @param applyIds 處理的申請ID清單
 */
@Parcelize


data class GroupApplyStatusParam (

    @Json(name = "status")
    val status: ApplyStatus? = null,

    /* 處理的申請ID清單 */
    @Json(name = "applyIds")
    val applyIds: kotlin.collections.List<kotlin.String>? = null

) : Parcelable

