/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.IGroupRequirementQuestion

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 加入社團的要求項目
 *
 * @param createUnixTime 創建時間
 * @param updateUnixTime 更新時間
 * @param questions 題目
 */
@Parcelize


data class GroupRequirement (

    /* 創建時間 */
    @Json(name = "createUnixTime")
    val createUnixTime: kotlin.Long? = null,

    /* 更新時間 */
    @Json(name = "updateUnixTime")
    val updateUnixTime: kotlin.Long? = null,

    /* 題目 */
    @Json(name = "questions")
    val questions: kotlin.collections.List<IGroupRequirementQuestion>? = null

) : Parcelable

