/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.Category
import com.cmoney.fanciapi.fanci.model.ColorTheme
import com.cmoney.fanciapi.fanci.model.IUserContext

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 群組
 *
 * @param id 唯一識別
 * @param name 社團命名
 * @param description 社團描述
 * @param isNeedApproval 加入是否需要審核
 * @param coverImageUrl 封面圖
 * @param thumbnailImageUrl 縮圖
 * @param categories 社團下的分類
 * @param weight 系統排序權重
 * @param creatorId 創立者
 * @param createUnixTime 創立時間
 * @param updateUnixTime 更新時間
 * @param memberCount 會員總數
 * @param colorSchemeGroupKey 
 * @param userContext 
 */
@Parcelize


data class Group (

    /* 唯一識別 */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* 社團命名 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* 社團描述 */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* 加入是否需要審核 */
    @Json(name = "isNeedApproval")
    val isNeedApproval: kotlin.Boolean? = null,

    /* 封面圖 */
    @Json(name = "coverImageUrl")
    val coverImageUrl: kotlin.String? = null,

    /* 縮圖 */
    @Json(name = "thumbnailImageUrl")
    val thumbnailImageUrl: kotlin.String? = null,

    /* 社團下的分類 */
    @Json(name = "categories")
    val categories: kotlin.collections.List<Category>? = null,

    /* 系統排序權重 */
    @Json(name = "weight")
    val weight: kotlin.Long? = null,

    /* 創立者 */
    @Json(name = "creatorId")
    val creatorId: kotlin.String? = null,

    /* 創立時間 */
    @Json(name = "createUnixTime")
    val createUnixTime: kotlin.Long? = null,

    /* 更新時間 */
    @Json(name = "updateUnixTime")
    val updateUnixTime: kotlin.Long? = null,

    /* 會員總數 */
    @Json(name = "memberCount")
    val memberCount: kotlin.Int? = null,

    @Json(name = "ColorSchemeGroupKey")
    val colorSchemeGroupKey: ColorTheme? = null,

    @Json(name = "userContext")
    val userContext: IUserContext? = null

) : Parcelable

