/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.FanciRole

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 社團會員 全部角色資訊
 *
 * @param id 使用者id
 * @param roleInfos 角色資訊(最高)
 */
@Parcelize


data class GroupMemberRoleInfos (

    /* 使用者id */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* 角色資訊(最高) */
    @Json(name = "roleInfos")
    val roleInfos: kotlin.collections.List<FanciRole>? = null

) : Parcelable

