/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.ColorTheme

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 新增社團的參數
 *
 * @param name 社團命名
 * @param description 社團簡介
 * @param isNeedApproval true: 非公開(需審核)  false: 公開(不用審核)
 * @param coverImageUrl 社團封面
 * @param thumbnailImageUrl 社團縮圖
 * @param colorSchemeGroupKey 
 */
@Parcelize


data class GroupParam (

    /* 社團命名 */
    @Json(name = "name")
    val name: kotlin.String,

    /* 社團簡介 */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* true: 非公開(需審核)  false: 公開(不用審核) */
    @Json(name = "isNeedApproval")
    val isNeedApproval: kotlin.Boolean? = null,

    /* 社團封面 */
    @Json(name = "coverImageUrl")
    val coverImageUrl: kotlin.String? = null,

    /* 社團縮圖 */
    @Json(name = "thumbnailImageUrl")
    val thumbnailImageUrl: kotlin.String? = null,

    @Json(name = "colorSchemeGroupKey")
    val colorSchemeGroupKey: ColorTheme? = null

) : Parcelable

