/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 社團命名
 * @param description 社團簡介
 * @param isNeedApproval 社團是否為開放
 * @param coverImage 社團封面
 * @param thumbnailImage 社團縮圖
 */


data class GroupParam (

    /* 社團命名 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* 社團簡介 */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* 社團是否為開放 */
    @Json(name = "isNeedApproval")
    val isNeedApproval: kotlin.Boolean? = null,

    /* 社團封面 */
    @Json(name = "coverImage")
    val coverImage: kotlin.String? = null,

    /* 社團縮圖 */
    @Json(name = "thumbnailImage")
    val thumbnailImage: kotlin.String? = null

)

