/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.GroupRequirementApply

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 社團申請資訊
 *
 * @param hasApplied 是否有申請過
 * @param apply 
 */
@Parcelize


data class GroupRequirementApplyInfo (

    /* 是否有申請過 */
    @Json(name = "hasApplied")
    val hasApplied: kotlin.Boolean? = null,

    @Json(name = "apply")
    val apply: GroupRequirementApply? = null

) : Parcelable

