/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.GroupRequirementQuestion

import com.squareup.moshi.Json

/**
 * 新增社團申請的題目
 *
 * @param questions 題目組合
 */


data class GroupRequirementParam (

    /* 題目組合 */
    @Json(name = "questions")
    val questions: kotlin.collections.List<GroupRequirementQuestion>? = null

)

