/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param editGroup 
 * @param rearrangeChannelCategory 
 * @param setGroupPublicity 
 * @param createOrEditCategory 
 * @param deleteCategory 
 * @param createOrEditChannel 
 * @param setAnnouncement 
 * @param deleteChannel 
 * @param createOrEditRole 
 * @param deleteRole 
 * @param rearrangeRoles 
 * @param assignRole 
 * @param approveJoinApplies 
 * @param deleteMemberMessage 
 * @param banOrKickMember 
 */
@Parcelize


data class GroupPermission (

    @Json(name = "editGroup")
    val editGroup: kotlin.Boolean? = null,

    @Json(name = "rearrangeChannelCategory")
    val rearrangeChannelCategory: kotlin.Boolean? = null,

    @Json(name = "setGroupPublicity")
    val setGroupPublicity: kotlin.Boolean? = null,

    @Json(name = "createOrEditCategory")
    val createOrEditCategory: kotlin.Boolean? = null,

    @Json(name = "deleteCategory")
    val deleteCategory: kotlin.Boolean? = null,

    @Json(name = "createOrEditChannel")
    val createOrEditChannel: kotlin.Boolean? = null,

    @Json(name = "setAnnouncement")
    val setAnnouncement: kotlin.Boolean? = null,

    @Json(name = "deleteChannel")
    val deleteChannel: kotlin.Boolean? = null,

    @Json(name = "createOrEditRole")
    val createOrEditRole: kotlin.Boolean? = null,

    @Json(name = "deleteRole")
    val deleteRole: kotlin.Boolean? = null,

    @Json(name = "rearrangeRoles")
    val rearrangeRoles: kotlin.Boolean? = null,

    @Json(name = "assignRole")
    val assignRole: kotlin.Boolean? = null,

    @Json(name = "approveJoinApplies")
    val approveJoinApplies: kotlin.Boolean? = null,

    @Json(name = "deleteMemberMessage")
    val deleteMemberMessage: kotlin.Boolean? = null,

    @Json(name = "banOrKickMember")
    val banOrKickMember: kotlin.Boolean? = null

) : Parcelable

