/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param counts 各種互動數統計
 */


data class IEmojiCount (

    /* 各種互動數統計 */
    @Json(name = "counts")
    val counts: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null

)

