/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.MediaType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param resourceLink 
 * @param type 
 */


data class IMedia (

    @Json(name = "resourceLink")
    val resourceLink: kotlin.String? = null,

    @Json(name = "type")
    val type: MediaType? = null

)

