/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 多媒體檔案 (個體)
 *
 * @param resourceLink 連結
 * @param type 媒體類型 (原本是Enum 但因為新增前端就要做強更 所以改成string彈性較高)<br></br>  圖片 (Image), 影片 (Video), 音檔 (Audio), 文檔 (Txt), PDF檔 (Pdf)
 * @param isNeedAuthenticate 媒體是否需要內部驗證
 */
@Parcelize


data class IMedia (

    /* 連結 */
    @Json(name = "resourceLink")
    val resourceLink: kotlin.String? = null,

    /* 媒體類型 (原本是Enum 但因為新增前端就要做強更 所以改成string彈性較高)<br></br>  圖片 (Image), 影片 (Video), 音檔 (Audio), 文檔 (Txt), PDF檔 (Pdf) */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* 媒體是否需要內部驗證 */
    @Json(name = "isNeedAuthenticate")
    val isNeedAuthenticate: kotlin.Boolean? = null

) : Parcelable

