/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 時間區段
 *
 * @param start 開始時間
 * @param end 結束時間
 */
@Parcelize


data class IntervalDateRangeParam (

    /* 開始時間 */
    @Json(name = "start")
    val start: java.time.OffsetDateTime? = null,

    /* 結束時間 */
    @Json(name = "end")
    val end: java.time.OffsetDateTime? = null

) : Parcelable

