/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.GroupMember
import com.cmoney.fanciapi.fanci.model.MediaIChatContent

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param author 
 * @param content 
 * @param isDeleted 是否刪除
 */
@Parcelize


data class IReplyMessage (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "author")
    val author: GroupMember? = null,

    @Json(name = "content")
    val content: MediaIChatContent? = null,

    /* 是否刪除 */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null

) : Parcelable

