/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 投票活動Id
 * @param title 標題
 */
@Parcelize


data class IReplyVoting (

    /* 投票活動Id */
    @Json(name = "id")
    val id: kotlin.Long? = null,

    /* 標題 */
    @Json(name = "title")
    val title: kotlin.String? = null

) : Parcelable

