/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 使用者個人化關聯資訊 (若未帶使用者資訊則為null)
 *
 * @param unreadCount 使用者當前未讀數
 */
@Parcelize


data class IUserContext (

    /* 使用者當前未讀數 */
    @Json(name = "unreadCount")
    val unreadCount: kotlin.Long? = null

) : Parcelable

