/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param cmoneyMemberId 
 * @param name 
 * @param thumbNail 
 * @param serialNumber 
 * @param createUnixTime 
 * @param updateUnixTime 
 */
@Parcelize


data class IUser (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "cmoneyMemberId")
    val cmoneyMemberId: kotlin.Int? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "thumbNail")
    val thumbNail: kotlin.String? = null,

    @Json(name = "serialNumber")
    val serialNumber: kotlin.Long? = null,

    @Json(name = "createUnixTime")
    val createUnixTime: kotlin.Long? = null,

    @Json(name = "updateUnixTime")
    val updateUnixTime: kotlin.Long? = null

) : Parcelable

