/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.Media

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param text 
 * @param medias 
 */
@Parcelize


data class MediaIChatContent (

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "medias")
    val medias: kotlin.collections.List<Media>? = null

) : Parcelable

