/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.AudioContent
import com.cmoney.fanciapi.fanci.model.ImageContent
import com.cmoney.fanciapi.fanci.model.MediaType
import com.cmoney.fanciapi.fanci.model.PdfContent
import com.cmoney.fanciapi.fanci.model.TxtContent
import com.cmoney.fanciapi.fanci.model.VideoContent

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param resourceLink 
 * @param type 
 * @param isNeedAuthenticate 
 * @param image 
 * @param audio 
 * @param video 
 * @param txt 
 * @param pdf 
 */
@Parcelize


data class Media (

    @Json(name = "resourceLink")
    val resourceLink: kotlin.String? = null,

    @Json(name = "type")
    val type: MediaType? = null,

    @Json(name = "isNeedAuthenticate")
    val isNeedAuthenticate: kotlin.Boolean? = null,

    @Json(name = "image")
    val image: ImageContent? = null,

    @Json(name = "audio")
    val audio: AudioContent? = null,

    @Json(name = "video")
    val video: VideoContent? = null,

    @Json(name = "txt")
    val txt: TxtContent? = null,

    @Json(name = "pdf")
    val pdf: PdfContent? = null

) : Parcelable

