/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.AudioContent
import com.cmoney.fanciapi.fanci.model.ImageContent
import com.cmoney.fanciapi.fanci.model.PdfContent
import com.cmoney.fanciapi.fanci.model.TxtContent
import com.cmoney.fanciapi.fanci.model.VideoContent
import com.cmoney.fanciapi.fanci.model.VoiceMessageContent

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 媒體
 *
 * @param resourceLink 連結
 * @param type 媒體類型 (原本是Enum 但因為新增前端就要做強更 所以改成string彈性較高)<br></br>  圖片 (Image), 影片 (Video), 音檔 (Audio), 文檔 (Txt), PDF檔 (Pdf), VoiceMessage(語音訊息)
 * @param isNeedAuthenticate 媒體是否需要內部驗證
 * @param image 
 * @param audio 
 * @param video 
 * @param txt 
 * @param pdf 
 * @param voiceMessage 
 */
@Parcelize


data class Media (

    /* 連結 */
    @Json(name = "resourceLink")
    val resourceLink: kotlin.String? = null,

    /* 媒體類型 (原本是Enum 但因為新增前端就要做強更 所以改成string彈性較高)<br></br>  圖片 (Image), 影片 (Video), 音檔 (Audio), 文檔 (Txt), PDF檔 (Pdf), VoiceMessage(語音訊息) */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* 媒體是否需要內部驗證 */
    @Json(name = "isNeedAuthenticate")
    val isNeedAuthenticate: kotlin.Boolean? = null,

    @Json(name = "image")
    val image: ImageContent? = null,

    @Json(name = "audio")
    val audio: AudioContent? = null,

    @Json(name = "video")
    val video: VideoContent? = null,

    @Json(name = "txt")
    val txt: TxtContent? = null,

    @Json(name = "pdf")
    val pdf: PdfContent? = null,

    @Json(name = "voiceMessage")
    val voiceMessage: VoiceMessageContent? = null

) : Parcelable

