/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: image,video,audio,txt,pdf
 */

enum class MediaType(val value: kotlin.String) {

    @Json(name = "Image")
    image("Image"),

    @Json(name = "Video")
    video("Video"),

    @Json(name = "Audio")
    audio("Audio"),

    @Json(name = "Txt")
    txt("Txt"),

    @Json(name = "Pdf")
    pdf("Pdf");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MediaType) "$data" else null

        /**
         * Returns a valid [MediaType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MediaType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

