/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 訊息id 參數
 *
 * @param messageId 訊息id
 */


data class MessageIdParam (

    /* 訊息id */
    @Json(name = "messageId")
    val messageId: kotlin.String

)

