/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.CategoryOrder

import com.squareup.moshi.Json

/**
 * 
 *
 * @param groupId 
 * @param categoryOrders 
 */


data class OrderParam (

    @Json(name = "groupId")
    val groupId: kotlin.String? = null,

    @Json(name = "categoryOrders")
    val categoryOrders: kotlin.collections.List<CategoryOrder>? = null

)

