/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param spacePermissionIds 
 * @param isAdd 
 */
@Parcelize


data class PatchPermissionParam (

    @Json(name = "spacePermissionIds")
    val spacePermissionIds: kotlin.collections.List<kotlin.Int>? = null,

    @Json(name = "isAdd")
    val isAdd: kotlin.Boolean? = null

) : Parcelable

