/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.Permission

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param haveNextPage 
 * @param nextWeight 
 * @param items 
 */
@Parcelize


data class PermissionPaging (

    @Json(name = "haveNextPage")
    val haveNextPage: kotlin.Boolean? = null,

    @Json(name = "nextWeight")
    val nextWeight: kotlin.Long? = null,

    @Json(name = "items")
    val items: kotlin.collections.List<Permission>? = null

) : Parcelable

