/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param name 權限名稱
 * @param description 權限描述
 * @param displayName 
 * @param highlight 
 */
@Parcelize


data class Permission (

    @Json(name = "id")
    val id: kotlin.String? = null,

    /* 權限名稱 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* 權限描述 */
    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    @Json(name = "highlight")
    val highlight: kotlin.Boolean? = null

) : Parcelable

