/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param packId 
 * @param type 
 * @param subjectId 
 * @param roleId 
 * @param roleName 
 * @param saleBelong 
 * @param isSubscribed 
 * @param paymentDate 
 * @param nextPaymentAlert 
 */
@Parcelize


data class PurchasedRole (

    @Json(name = "packId")
    val packId: kotlin.Long? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "subjectId")
    val subjectId: kotlin.Int? = null,

    @Json(name = "roleId")
    val roleId: kotlin.Long? = null,

    @Json(name = "roleName")
    val roleName: kotlin.String? = null,

    @Json(name = "saleBelong")
    val saleBelong: kotlin.String? = null,

    @Json(name = "isSubscribed")
    val isSubscribed: kotlin.Boolean? = null,

    @Json(name = "paymentDate")
    val paymentDate: String? = null,

    @Json(name = "nextPaymentAlert")
    val nextPaymentAlert: kotlin.String? = null

) : Parcelable

