/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.PurchasedRole

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param vipSaleId 
 * @param vipSaleName 
 * @param purchasedRoles 
 */
@Parcelize


data class PurchasedSale (

    @Json(name = "vipSaleId")
    val vipSaleId: kotlin.Long? = null,

    @Json(name = "vipSaleName")
    val vipSaleName: kotlin.String? = null,

    @Json(name = "purchasedRoles")
    val purchasedRoles: kotlin.collections.List<PurchasedRole>? = null

) : Parcelable

