/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.VipSale

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param vipSalePlans 
 * @param roleName 
 * @param saleBelong 
 * @param isSubscribed 
 * @param currentDeadline 
 * @param paymentDate 
 * @param nextPaymentAlert 
 */
@Parcelize


data class PurchasedRole (

    @Json(name = "vipSalePlans")
    val vipSalePlans: kotlin.collections.List<VipSale>? = null,

    @Json(name = "roleName")
    val roleName: kotlin.String? = null,

    @Json(name = "saleBelong")
    val saleBelong: kotlin.String? = null,

    @Json(name = "isSubscribed")
    val isSubscribed: kotlin.Boolean? = null,

    @Json(name = "currentDeadline")
    val currentDeadline: java.time.OffsetDateTime? = null,

    @Json(name = "paymentDate")
    val paymentDate: java.time.OffsetDateTime? = null,

    @Json(name = "nextPaymentAlert")
    val nextPaymentAlert: kotlin.String? = null

) : Parcelable

