/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 前端推播設定分類
 *
 * Values: silent,newPost,newStory
 */

enum class PushNotificationSettingType(val value: kotlin.String) {

    @Json(name = "Silent")
    silent("Silent"),

    @Json(name = "NewPost")
    newPost("NewPost"),

    @Json(name = "NewStory")
    newStory("NewStory");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PushNotificationSettingType) "$data" else null

        /**
         * Returns a valid [PushNotificationSettingType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PushNotificationSettingType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

