/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 已讀狀態參數
 *
 * @param serialNumber 已讀訊息的流水號
 */
@Parcelize


data class ReadStatusParam (

    /* 已讀訊息的流水號 */
    @Json(name = "serialNumber")
    val serialNumber: kotlin.Long

) : Parcelable

