/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.Channel
import com.cmoney.fanciapi.fanci.model.GroupMember
import com.cmoney.fanciapi.fanci.model.ReportProcessStatus
import com.cmoney.fanciapi.fanci.model.ReportReason

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param reportee 
 * @param channel 
 * @param contentId 
 * @param contentSnapshot 
 * @param processStatus 
 * @param mostReason 
 * @param reporters 
 * @param createUnixTime 
 * @param updateUnixTime 
 */
@Parcelize


data class ReportInformation (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "reportee")
    val reportee: GroupMember? = null,

    @Json(name = "channel")
    val channel: Channel? = null,

    @Json(name = "contentId")
    val contentId: kotlin.String? = null,

    @Json(name = "contentSnapshot")
    val contentSnapshot: kotlin.String? = null,

    @Json(name = "processStatus")
    val processStatus: ReportProcessStatus? = null,

    @Json(name = "mostReason")
    val mostReason: ReportReason? = null,

    @Json(name = "reporters")
    val reporters: kotlin.collections.List<GroupMember>? = null,

    @Json(name = "createUnixTime")
    val createUnixTime: kotlin.Long? = null,

    @Json(name = "updateUnixTime")
    val updateUnixTime: kotlin.Long? = null

) : Parcelable

