/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.ChannelTabType
import com.cmoney.fanciapi.fanci.model.ReportReason

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param tabType 
 * @param contentId 
 * @param reason 
 */
@Parcelize


data class ReportParm (

    @Json(name = "tabType")
    val tabType: ChannelTabType? = null,

    @Json(name = "contentId")
    val contentId: kotlin.String? = null,

    @Json(name = "reason")
    val reason: ReportReason? = null

) : Parcelable

