/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: 紅,橘,黃,綠,藍綠,藍,紫,粉
 */

enum class RoleColor(val value: kotlin.String) {

    @Json(name = "紅")
    紅("紅"),

    @Json(name = "橘")
    橘("橘"),

    @Json(name = "黃")
    黃("黃"),

    @Json(name = "綠")
    綠("綠"),

    @Json(name = "藍綠")
    藍綠("藍綠"),

    @Json(name = "藍")
    藍("藍"),

    @Json(name = "紫")
    紫("紫"),

    @Json(name = "粉")
    粉("粉");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RoleColor) "$data" else null

        /**
         * Returns a valid [RoleColor] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RoleColor? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

