/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.RoleColor

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 新增角色參數
 *
 * @param name 角色名稱
 * @param permissionIds Fanci權限ID清單  參考 /api/v1/Permission 清單內容
 * @param color 
 * @param isAdmin 
 */
@Parcelize


data class RoleParam (

    /* 角色名稱 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Fanci權限ID清單  參考 /api/v1/Permission 清單內容 */
    @Json(name = "permissionIds")
    val permissionIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "color")
    val color: RoleColor? = null,

    @Json(name = "isAdmin")
    val isAdmin: kotlin.Boolean? = null

) : Parcelable

