/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: red,orange,yellow,green,blueGreen,blue,purple,pink
 */

enum class RoleColor(val value: kotlin.String) {

    @Json(name = "SpecialColor_Red")
    red("SpecialColor_Red"),

    @Json(name = "SpecialColor_Orange")
    orange("SpecialColor_Orange"),

    @Json(name = "SpecialColor_Yellow")
    yellow("SpecialColor_Yellow"),

    @Json(name = "SpecialColor_Green")
    green("SpecialColor_Green"),

    @Json(name = "SpecialColor_BlueGreen")
    blueGreen("SpecialColor_BlueGreen"),

    @Json(name = "SpecialColor_Blue")
    blue("SpecialColor_Blue"),

    @Json(name = "SpecialColor_Purple")
    purple("SpecialColor_Purple"),

    @Json(name = "SpecialColor_Pink")
    pink("SpecialColor_Pink");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RoleColor) "$data" else null

        /**
         * Returns a valid [RoleColor] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RoleColor? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

