/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param permissionIds Fanci權限ID清單  參考 /api/v1/Permission 清單內容
 */


data class RoleParam (

    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Fanci權限ID清單  參考 /api/v1/Permission 清單內容 */
    @Json(name = "permissionIds")
    val permissionIds: kotlin.collections.List<kotlin.String>? = null

)

