/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 角色資訊
 *
 * @param id 角色Id
 * @param name 角色名稱
 * @param color 角色顏色
 */
@Parcelize


data class RoleInfo (

    /* 角色Id */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* 角色名稱 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* 角色顏色 */
    @Json(name = "color")
    val color: kotlin.String? = null

) : Parcelable

