/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.IntervalDateRangeParam
import com.cmoney.fanciapi.fanci.model.MessageServiceType

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 訊息搜尋條件
 *
 * @param authorId 作者 Id
 * @param nickname 作者暱稱
 * @param searchText 搜尋文章內容
 * @param groupIds 群組社團
 * @param channelIds 頻道
 * @param categoryIds 分類
 * @param messageServiceTypes 聊天室/貼文
 * @param modifyTime 
 * @param createTime 
 */
@Parcelize


data class SearchMessageParam (

    /* 作者 Id */
    @Json(name = "authorId")
    val authorId: kotlin.String? = null,

    /* 作者暱稱 */
    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    /* 搜尋文章內容 */
    @Json(name = "searchText")
    val searchText: kotlin.String? = null,

    /* 群組社團 */
    @Json(name = "groupIds")
    val groupIds: kotlin.collections.List<kotlin.String>? = null,

    /* 頻道 */
    @Json(name = "channelIds")
    val channelIds: kotlin.collections.List<kotlin.String>? = null,

    /* 分類 */
    @Json(name = "categoryIds")
    val categoryIds: kotlin.collections.List<kotlin.String>? = null,

    /* 聊天室/貼文 */
    @Json(name = "messageServiceTypes")
    val messageServiceTypes: kotlin.collections.List<MessageServiceType>? = null,

    @Json(name = "modifyTime")
    val modifyTime: IntervalDateRangeParam? = null,

    @Json(name = "createTime")
    val createTime: IntervalDateRangeParam? = null

) : Parcelable

