/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param fileName 
 * @param fileSize 
 * @param thumbnailUrl 
 */
@Parcelize


data class TxtContent (

    @Json(name = "fileName")
    val fileName: kotlin.String? = null,

    @Json(name = "fileSize")
    val fileSize: kotlin.Long? = null,

    @Json(name = "thumbnailUrl")
    val thumbnailUrl: kotlin.String? = null

) : Parcelable

