/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 更新 社團 公開或非公開
 *
 * @param isNeedApproval true: 非公開(需審核)  false: 公開(不用審核)
 */
@Parcelize


data class UpdateIsNeedApprovalParam (

    /* true: 非公開(需審核)  false: 公開(不用審核) */
    @Json(name = "isNeedApproval")
    val isNeedApproval: kotlin.Boolean? = null

) : Parcelable

