/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.BanPeriodOption
import com.cmoney.fanciapi.fanci.model.User

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param user 
 * @param startDateTime 
 * @param endDateTime 
 * @param panaltySeconds 
 * @param periodOption 
 */
@Parcelize


data class UserBanInformation (

    @Json(name = "user")
    val user: User? = null,

    @Json(name = "startDateTime")
    val startDateTime: kotlin.Long? = null,

    @Json(name = "endDateTime")
    val endDateTime: kotlin.Long? = null,

    @Json(name = "panaltySeconds")
    val panaltySeconds: kotlin.Long? = null,

    @Json(name = "periodOption")
    val periodOption: BanPeriodOption? = null

) : Parcelable

