/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 使用者陣列參數
 *
 * @param userIds Fanci 用戶 ID
 */
@Parcelize


data class UseridsParam (

    /* Fanci 用戶 ID */
    @Json(name = "userIds")
    val userIds: kotlin.collections.List<kotlin.String>? = null

) : Parcelable

