/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.BuffStatus
import com.cmoney.fanciapi.fanci.model.User

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param user 
 * @param buffs 
 */
@Parcelize


data class UserBuffInformation (

    @Json(name = "user")
    val user: User? = null,

    @Json(name = "buffs")
    val buffs: kotlin.collections.List<BuffStatus>? = null

) : Parcelable

