/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cmoney.fanciapi.fanci.model

import com.cmoney.fanciapi.fanci.model.VotingOption

import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 創建投票參數
 *
 * @param title 標題
 * @param votingOptions 選項
 * @param isMultipleChoice 是否能多選
 * @param isAnonymous 是否匿名投票 (不記名投票)
 */
@Parcelize


data class VotingParam (

    /* 標題 */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* 選項 */
    @Json(name = "votingOptions")
    val votingOptions: kotlin.collections.List<VotingOption>? = null,

    /* 是否能多選 */
    @Json(name = "isMultipleChoice")
    val isMultipleChoice: kotlin.Boolean? = null,

    /* 是否匿名投票 (不記名投票) */
    @Json(name = "isAnonymous")
    val isAnonymous: kotlin.Boolean? = null

) : Parcelable

